# Dynamic configuration
http:

  routers:
    router-homeassistant:
      entryPoints:
        - websecure
      rule: Host(`ha.[yourDomain]`)
      service: service-homeassistant
      tls:
        certResolver: letsencrypt

  services:
    service-homeassistant:
      loadBalancer:
        servers:
        - url: "http://[ip to home assistant]]:8123"

  middlewares:
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    user-auth:
      basicAuth:
        users:
          - "[UserName]:[generatedEncryptedPassword]"

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12